### ISSUE TITLE
Falling onto a ladder from the side doesn't cause fall damage

### ISSUE THREAD

**Issue by 0ffz** [CultOfClang/BoneHurtingJuice#10]
If I fall directly on a ladder, the damage is taken, but if i fall, then approach it from the side it appears that no damag is dealt (on the test server). Perhaps the ladder reduces your velocity or fall distance before the check kicks in. I remember for dangerous waters, just checking the block beneath wasn't enough, it had to be a couple blocks around that block beneath you.

**Comment by 0ffz** [comment]
Similarly, just barely touching water as you fall will not deal the fall damage, while falling directly into it does.

**Comment by lizelive** [comment]
fixed
