### ISSUE TITLE
Corona virus and other code issues

### ISSUE THREAD

**Issue by Derongan** [CultOfClang/BoneHurtingJuice#3]
Nit. why so much space, also im assuming this is kotlin magic: https://github.com/CultOfClang/BoneHurtingJuice/blob/8769b03df0c3ae84710a10d055f287d51b1b6f0a/src/main/kotlin/org/cultofclang/bonehurtingjuice/BoneHurtPlugin.kt#L24

Why does this class exist? its not used - https://github.com/CultOfClang/BoneHurtingJuice/blob/master/src/main/kotlin/org/cultofclang/bonehurtingjuice/Config.kt

This looks like it should be deleted - https://github.com/CultOfClang/BoneHurtingJuice/blob/8769b03df0c3ae84710a10d055f287d51b1b6f0a/src/main/kotlin/org/cultofclang/bonehurtingjuice/MoveListener.kt#L24

I thought we settled on invulnerable - https://github.com/CultOfClang/BoneHurtingJuice/blob/8769b03df0c3ae84710a10d055f287d51b1b6f0a/src/main/kotlin/org/cultofclang/bonehurtingjuice/MoveListener.kt#L41

This seems questionable, but I assume you've tested it? If a player has a rocket for example does the sequence of updates make sense? (Rocket upwards before hitting cactus, do they take the cactus damage?)  - https://github.com/CultOfClang/BoneHurtingJuice/blob/8769b03df0c3ae84710a10d055f287d51b1b6f0a/src/main/kotlin/org/cultofclang/bonehurtingjuice/MoveListener.kt#L92

This doesn't seem to do anything of value - https://github.com/CultOfClang/BoneHurtingJuice/blob/76cf85a1441177613ca6e958d20fcc6dbb32226b/src/main/kotlin/org/cultofclang/bonehurtingjuice/command/InfoCmd.kt#L7

**Comment by lizelive** [comment]
fixed
